### 댓글 등록
POST https://demo-boost-a.onrender.com/api/posts/1/comment
Content-Type: application/json

{
  "nickname": "JohnDoe",
  "content": "This is a test comment",
  "password": "testpassword123"
}

### 댓글 목록 조회
GET https://demo-boost-a.onrender.com/api/posts/1/comment?page=1&pageSize=10

### 댓글 수정
PUT https://demo-boost-a.onrender.com/api/comment/1
Content-Type: application/json

{
  "nickname": "JohnDoe",
  "content": "This is an updated test comment",
  "password": "testpassword123"
}

### 댓글 삭제
DELETE https://demo-boost-a.onrender.com/api/comment/1
Content-Type: application/json

{
  "password": "testpassword123"
}


