POST http://localhost:3000/api/groups
Content-Type: application/json

{
	"name": "철수",
	"password": "string",
	"imageUrl": "string",
	"isPublic": true,
	"introduction": "string"
}

### 

GET http://localhost:3000/api/groups



